feat(cluster): add cluster benchmark in k8s

diff --git a/scripts/k8s/k8s-common b/scripts/k8s/k8s-common
--- a/scripts/k8s/k8s-common
+++ b/scripts/k8s/k8s-common
@@ -51,31 +51,52 @@ function f_wait_for_dns() {
 #####################################################################################
 # Construct JVM_OPTS with dynamic interface lookup
 function f_set_jvm_opts() {
-
-
   # If this is not a DPDK test...
-  if [[ "${BENCHMARK_TYPE}" =~ dpdk$ ]]
-    then
+  if [[ "${BENCHMARK_TYPE}" = dpdk$ ]]; then
       # Don't select an interface
       SELECT_INTERFACE=""
-    else
-      # Look up the interface we're supposed to use.
-      case ${POD_NAME} in
-        aeron-benchmark-0)
-          LOCAL_IP="$( host "${NODE0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
-          ;;
-        aeron-benchmark-1)
-          LOCAL_IP="$( host "${NODE1_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
-          ;;
-        *)
-          echo "Error: Could not resolve IP for POD ${POD_NAME}"
-          exit 1
-          ;;
-      esac
-      # Specifically select the interface to use.
-      SELECT_INTERFACE="|interface=${LOCAL_IP}/32"
-
+  elif [[ "${BENCHMARK_TYPE}" =~ cluster$ ]]; then
+    case ${POD_NAME} in
+      aeron-cluster-0)
+        LOCAL_IP="$(host "${NODE0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      aeron-cluster-1)
+        LOCAL_IP="$(host "${NODE1_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      aeron-cluster-2)
+        LOCAL_IP="$(host "${NODE2_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      aeron-cluster-client)
+        LOCAL_IP="$(host "${CLIENT0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      *)
+        echo "Error: Could not resolve IP for POD ${POD_NAME}"
+        exit 1
+        ;;
+    esac
+    # Specifically select the interface to use.
+    SELECT_INTERFACE="|interface=${LOCAL_IP}/32"
+  else
+    # Look up the interface we're supposed to use.
+    case ${POD_NAME} in
+      aeron-benchmark-0)
+        LOCAL_IP="$( host "${NODE0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      aeron-benchmark-1)
+        LOCAL_IP="$( host "${NODE1_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+        ;;
+      *)
+        echo "Error: Could not resolve IP for POD ${POD_NAME}"
+        exit 1
+        ;;
+    esac
+    # Specifically select the interface to use.
+    SELECT_INTERFACE="|interface=${LOCAL_IP}/32"
   fi
+
+# # Bernardo's update to set up cluster instead of client/server
+#   export JVM_OPTS="-Duk.co.real_logic.benchmarks.remote.output.directory=/dev/shm/results \
+# -Duk.co.real_logic.benchmarks.aeron.remote.embedded.media.driver=false"
 
   export JVM_OPTS="-Duk.co.real_logic.benchmarks.remote.output.directory=/dev/shm/results \
 -Duk.co.real_logic.benchmarks.aeron.remote.embedded.media.driver=false \
